language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - PACKAGE_NAME=urequest PACKAGE_VERSION=0.0.6
before_install:
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-get update
  - sudo apt-get -y install bats
  - pip install pip==20.2
  - pip install -r requirements-dev.txt -U
script:
    - ./analyse-source-code.sh
    - bats --pretty test-package.bats
after_success:
  - coveralls
notifications:
  email: false
