language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - PACKAGE_NAME=urequest PACKAGE_VERSION=0.0.6
before_install:
  - pip install pip -U
  - pip install -r requirements-dev.txt -U
script:
    - ./analyse-source-code.sh
    - ./test-package.sh
after_success:
  - coveralls
notifications:
  email: false
